name: Maven Compile Check

on:
  push:
    branches:
      - main
      - develop   # optional (add your working branches)

  pull_request:
    types: [closed]   # only when PR is closed (merged or not)

jobs:
  build:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - run: mvn compile
